# 
os:
  - linux

branches:
  only:
  - master

before_install:
- sudo apt-get update -qq
- sudo apt-get install --yes git
- sudo apt-get install --yes make
- sudo apt-get install --yes libreadline6-dev
- sudo apt-get install --yes gcc
- git clone --recursive https://github.com/jamiejennings/rosie-pattern-language.git /opt/rosie/
- cd /opt/rosie && make clean && make linux

language: python
script: 